<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper <?php if(Mage::helper('themeframework/settings')->getGeneral_BoxWide()=='box' && Mage::helper('themeframework/settings')->checkMobilePhp()==false):?><?php echo ' em-box-custom';?><?php endif;?>">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page two-columns-right">
		<?php echo Mage::helper('themeframework/bootstrapbase')->displayBootstrapV3($this, '2columns-right') ?>
		<?php echo $this->getChildHtml('global_cookie_notice') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
