<?php
    $id = $this->getData('wrapperId');
    $class = $this->getData('wrapperClass');
    $content = $this->getChildHtml('', true, true);
?>
<?php if (!empty($content)): ?>
	<?php if ($id || $class): ?>
		<div <?php if($id):?>id="<?php echo $id ?>"<?php endif;?> <?php if($class):?>class="<?php echo $class ?>"<?php endif;?>>
			<?php echo $content ?>
		</div>
	<?php else: ?>
		<?php echo $content ?>
	<?php endif ?>
<?php endif ?>