<div class="popup-subscribe">
	<div class="em-line-01 em-wrapper-newsletter newsletter-boder-input-act">
		<div class="em-block-title">
			<p class="h3"><span><?php echo $this->__('newsletter') ?></span></p>
		</div>
		<p><?php echo $this->__('Subscribe to our newsletter to get all news and exclusive offers.') ?></p>
		<div class="block block-subscribe">
			<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="em-popup-newsletter-validate-detail">
				<div class="block-content">
					<div class="form-subscribe-content">
						<div class="input-box">
						   <input type="text" name="email" id="popup-newsletter" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" />
						</div>
						<div class="actions">
							<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe')) ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
						</div>
					</div>
				</div>
			</form>
			 
		</div>
	</div>
	<script type="text/javascript">
		//<![CDATA[
			var searchFormPopup = new Varien.searchForm('em-popup-newsletter-validate-detail', 'popup-newsletter', '<?php echo $this->__('Sign up for your email ...') ?>'); 
			var newsletterSubscriberFormDetailPopup = new VarienForm('em-popup-newsletter-validate-detail');
		//]]>
	</script>
</div>