<?php
	$_products = $this->getProductCollection();
	$_helper = $this->helper('catalog/output');
	
	$limitproduct = $this->getLimitCount();
	$size = $_products->getSize();
	if($limitproduct == "" || $limitproduct > $size){
		$limitproduct = $size;
	}
	
	$w = $this->getThumbnailWidth();
	$h = $this->getThumbnailHeight();
	$_columnCount = $this->getColumnCount();
	$alt_img = $this->getAltImg();
    
    /* slider config */
	$idJs = "slide_".md5(uniqid(rand()));    
    if ($this->getData('slider_unique_id'))
		$idJs = $this->getData('slider_unique_id');
	$this->idJs = $idJs;
	$idTab = "em-filterproducts-tab-".md5(uniqid(rand()));
?>
<div id="<?php echo $idJs;?>" <?php if($this->getCustomClass()): ?>class="<?php echo $this->getCustomClass();?>"<?php endif; ?>>
	<?php if($this->getFrontendTitle()): ?>
	<div class="widget-title em-widget-title">
		<h3><span><?php echo $this->getFrontendTitle(); ?></span></h3>
	</div>
	<?php endif; ?>
    
	<?php if($this->getFrontendDescription()):?>
	<div class="desc"><?php echo $this->getFrontendDescription(); ?></div>
	<?php endif ?>
    
	<?php if ($limitproduct): ?>
	<div class="widget em-filterproducts-custom">
		<div class="widget-products em-widget-products tab-content">
			
			<?php $i=0; foreach ($_products as $_product): ?>
			
				<div class="main-product" id="<?php echo $idTab ?>-<?php echo $i ?>">
					<?php if ($this->getShowFrontend('thumb')): ?>
	    					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image loading-process">
	    						<?php if ($this->getShowFrontend('label') && Mage::helper('core')->isModuleEnabled('EM_Productlabels')):?>
	    						<!--show label product - label extension is required-->
	    						<?php Mage::helper('productlabels')->display($_product);?>
	    						<?php endif;?>
	                            
	    						<?php if ($alt_img): ?>                            
										<img class="em-alt-hover img-responsive em-img-lazy" src="<?php echo $this->getSkinUrl('images/loading.gif') ?>" data-original="<?php echo $this->helper('catalog/image')->init($_product, $alt_img)->resize($w,$h) ?>" width="<?php echo $w; ?>" height="<?php echo $h ;?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
    						<?php endif ?>
										<img class="img-responsive em-img-lazy <?php if ($alt_img): ?>em-alt-org<?php endif ?>" src="<?php echo $this->getSkinUrl('images/loading.gif') ?>" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w,$h) ?>" width="<?php echo $w; ?>" height="<?php echo $h ;?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />                        
							<span class="bkg-hover"></span>
	    					</a>
						<?php else: ?>
	    					<?php if ($this->getShowFrontend('label') && Mage::helper('core')->isModuleEnabled('EM_Productlabels')):?>
	    					<!--show label product - label extension is required-->
	    					<?php Mage::helper('productlabels')->display($_product);?>
	    					<?php endif;?>
						<?php endif; ?>
						<div class="product-shop">
							<div class="f-fix">
	                            <!--product reviews-->
								<?php if ($this->getShowFrontend('review')):?>
								     <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								<?php endif ; ?>
								<!--product price-->
	                            
								<!--product name-->
								<?php if ($this->getShowFrontend('name')):?>
								     <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
								<?php endif;?>
	                            
	                            <!-- sku -->
								<?php if ($this->getShowFrontend('sku')):?>
								     <p class="sku"><?php echo $_product->getSku(); ?></p>
								<?php endif ;?>
	                            
	                            
	                            <!-- price -->						
								<?php if ($this->getShowFrontend('price')):?>
									<?php if (Mage::helper('catalog')->canApplyMsrp($_product)):?>
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->__('Detail') ?></a>
									<?php else : ?>
										<?php echo $this->getPriceHtml($_product, true, "-emprice-".md5(uniqid(rand())) ) ?>
									<?php endif;?>
								<?php endif;?>
	                            
								<!--product description-->
								<?php if ($this->getShowFrontend('desc')):
									$desc = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
									if(strlen($desc)>80) {
										$strCutTitle = substr($desc, 0, 80);
										$desc = substr($strCutTitle, 0, strrpos($strCutTitle, ' '));
									}
								?>
								<p class="desc"><?php echo $desc; ?></p>
								<?php endif ;?>	
								
	                            <?php if($this->getShowFrontend('addtocart') || $this->getShowFrontend('addto')): ?>
	                                <div class="em-btn-addto">
	        							<!--product add to cart-->
	        							<?php if ($this->getShowFrontend('addtocart')):?>
	            							<?php if ($_product->isSaleable()): ?>
	            							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
	            							<?php else: ?>
	            							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
	            							<?php endif; ?>
	        							<?php endif; ?>
	        							<!--product add to compare-wishlist-->
	        							<?php if($this->getShowFrontend('addto')):?>
	        							<ul class="add-to-links">
	        								<?php if ($this->helper('wishlist')->isAllow()) : ?>
	        								<li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
	        								<?php endif; ?>
	        								<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
	        								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
	        								<?php endif; ?>
	        							</ul>
	        							<?php endif; ?>
	                                </div>
	                            <?php endif;?>
							</div>
						</div>
				</div>
				<?php if($i >= $limitproduct) break;?>
			
			<?php $i++;?>
			<?php endforeach; ?>
			<div class="tabs-nav <?php if($this->getData('slider_enable')): ?>owl-carousel owl-theme<?php endif;?> no_quickshop">
				<?php $j=0; foreach ($_products as $_product): ?>				
					<div class="<?php if($itemClass = $this->getData('item_class')) echo $itemClass.' '; ?>item<?php echo $_columnCount > 0 && $j%$_columnCount==0 || $_columnCount <= 0 && $j == 0 ?' first active':''; ?><?php echo $_columnCount > 0 && ($j+1)%$_columnCount==0 || $j+1 == $limitproduct ?' last':''; ?>"
						style="<?php echo $this->getItemWidth() ? 'width:'.$this->getItemWidth().'px;' : '' ?> <?php echo $this->getItemHeight() ? 'height:'.$this->getItemHeight().'px;' : '' ?> <?php echo $this->getItemSpacing() ? 'margin-right:'.$this->getItemSpacing().'px;' : '' ?>">						
	    					<a href="#<?php echo $idTab ?>-<?php echo $j ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-nav">	    							    			
	    						<img class="img-responsive <?php if ($alt_img): ?>em-alt-org<?php endif ?>" <?php if($this->getData('slider_lazyload')): ?>data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w,$h) ?>"<?php endif;?> src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w,$h) ?>" width="<?php echo $w; ?>" height="<?php echo $h ;?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />                        
	    					</a>									
					</div>
				<?php if($j >= $limitproduct) break;?>
                <?php $j++;?>
                <?php endforeach; ?>
			</div>	
			
		</div>
	</div>
<?php if($this->getData('slider_enable')): ?>
<script type="text/javascript">
//<![CDATA[
    (function($) {
        function easyTab(){
    		$('.tabs-nav').each(function(){					
				var $active, $content, $links = $(this).find('a.product-nav');
				$active = $($links.filter('[href="'+location.hash+'"]')[0] || $links[0]);
				$active.addClass('activeContent');
				
				$content = $($active[0].hash);					
				// Hide the remaining content
				$links.not($active).each(function () {						
					$(this.hash).hide();
				});

				// Bind the click event handler
				$(this).on('click', 'a.product-nav', function(e){
					// Make the old tab inactive.
					$active.removeClass('activeContent');
					$content.hide();

					// Update the variables with the new link and content
					$active = $(this);
					$content = $(this.hash);

					// Make the tab active.
					$active.addClass('activeContent');
					$content.show();
					setTimeout(function() { jQuery("#<?php echo $idJs ?> img.em-img-lazy").trigger("sporty") }, 1000);

					// Prevent the anchor's default click action
					e.preventDefault();
				});
			});
    
    	}
        function em_slider_init_widget_<?php echo $idJs ?>(){
            var owl = $("#<?php echo $idJs ?>").find('.owl-carousel'); 
            if(owl.length){            
                owl.owlCarousel({
                    //Basic Speeds
                    slideSpeed : <?php echo $this->getData('slider_speed') ? $this->getData('slider_speed') : '800' ?>,
                    rewindSpeed : <?php echo $this->getData('slider_rewindspeed') ? $this->getData('slider_rewindspeed') : '800' ?>,
                 
                    //Autoplay
                    autoPlay : <?php echo $this->getData('slider_autoplay') ? 'true' : 'false'?>,
                    lazyLoad : <?php echo $this->getData('slider_lazyload') ? 'true' : 'false'?>,
                    stopOnHover : <?php echo $this->getData('slider_stoponhover') ? 'true' : 'false'?>,
                    mouseDrag : <?php echo $this->getData('slider_mouse_drag') ? 'true' : 'false'?>,
                    touchDrag : <?php echo $this->getData('slider_touch_drag') ? 'true' : 'false'?>,    
                 
                    // Navigation
                    navigation : <?php echo $this->getData('slider_navigation') ? 'true' : 'false'?>,
                    navigationText : ["<?php echo $this->__('Previous')?>", "<?php echo $this->__('Next')?>"],
                    pagination : <?php echo $this->getData('slider_pagination') ? 'true' : 'false'?>,
                    paginationNumbers: <?php echo $this->getData('slider_pagination_numbers') ? 'true' : 'false'?>,                 
                    
                    <?php if(Mage::helper('themeframework/settings')->getGeneral_DisableResponsive(1)!=0):?>
                        // Responsive 
                        responsive: true,
                        items : <?php echo $this->getData('slider_items') ? $this->getData('slider_items'): 4 ?>, /*items above 1200px browser width*/
                        itemsDesktop : [1200,<?php echo $this->getData('slider_items_desktop') ? $this->getData('slider_items_desktop') : ($this->getData('slider_items') ? $this->getData('slider_items'): 4) ?>], /*//items between 1199px and 981px*/
                        itemsDesktopSmall : [992,<?php echo $this->getData('slider_items_desktop_small') ? $this->getData('slider_items_desktop_small') : ($this->getData('slider_items') ? $this->getData('slider_items'): 4) ?>],
                        itemsTablet: [768,<?php echo $this->getData('slider_items_tablet') ? $this->getData('slider_items_tablet') : ($this->getData('slider_items') ? $this->getData('slider_items'): 4) ?>],                
                        itemsMobile : [480,<?php echo $this->getData('slider_items_mobile') ? $this->getData('slider_items_mobile') :  ($this->getData('slider_items') ? $this->getData('slider_items'): 4) ?>],
                    <?php else:?>
                        responsive: false,
                        items : <?php echo $this->getData('slider_items') ? $this->getData('slider_items'): 4 ?>, /*items above 1200px browser width*/
                    <?php endif;?>
                 
                    // CSS Styles
                    baseClass : "owl-carousel",
                    theme : "owl-theme",
                    addClassActive : true,
                    scrollPerPage : <?php echo $this->getData('slider_scrollperpage') ? 'true' : 'false'?>
              });
			$("#<?php echo $idJs ?> .owl-controls").click(function(){
					if(jQuery("#<?php echo $idJs ?> img.em-img-lazy").length){
						var timeout = setTimeout(function() { jQuery("#<?php echo $idJs ?> img.em-img-lazy").trigger("sporty") }, 400);
					}
				});
          }
    	}
        $(document).ready(function(){            
            em_slider_init_widget_<?php echo $idJs ?>();
            easyTab();        
        });
    })(jQuery);
//]]>
</script>
    <?php endif;?>
    

    <script type="text/javascript">
    //<![CDATA[
        (function($) {
            $(function() {
                $("#<?php echo $idJs ?> img.em-img-lazy").lazyload({
                    event : "scroll resize scrollStop sporty",
                    placeholder: urlSkinsite+'images/loading.gif',
                    load : function(){
                        if ($(this).attr("src").indexOf('loading.gif') == -1) {
                            $(this).removeClass("em-img-lazy").addClass('em-lazy-loaded');
                            $(this).parent('.product-image').removeClass('loading-process');                  
                        }
                    }
                });
            }); 
        })(jQuery); 
    //]]>
    </script>
    
	<?php else:?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
	<?php endif; ?>
</div>